# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person_register.Position'),
            preserve_default=False,
        ),
    ]
